export type VocabularyEntry = {
  german: string;
  plural: string;
  phonetic: string;
  vietnamese: string;
  exampleGerman: string;
  exampleVietnamese: string;
  type: string;
  level: string;
};

export const vocabularyList: VocabularyEntry[] = [
  {
    german: "der Kopf",
    plural: "die Köpfe",
    phonetic: "/kɔpf/",
    vietnamese: "Đầu",
    exampleGerman: "Der Kopf tut weh, weil ich gestern gestürzt bin.",
    exampleVietnamese: "Đầu tôi đau, vì hôm qua tôi bị ngã.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "das Gesicht",
    plural: "die Gesichter",
    phonetic: "/gəˈzɪçt/",
    vietnamese: "Khuôn mặt",
    exampleGerman: "Das Gesicht des Kindes war voller Freude.",
    exampleVietnamese: "Khuôn mặt của đứa trẻ đầy niềm vui.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "das Haar",
    plural: "die Haare",
    phonetic: "/haːr/",
    vietnamese: "Tóc",
    exampleGerman: "Die Haare sind sehr lang, deshalb muss ich sie schneiden.",
    exampleVietnamese: "Tóc tôi rất dài, vì vậy tôi phải cắt.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Stirn",
    plural: "die Stirnen",
    phonetic: "/ʃtɪrn/",
    vietnamese: "Trán",
    exampleGerman: "Die Stirn ist manchmal ein Indikator für Stress.",
    exampleVietnamese: "Trán đôi khi là dấu hiệu của căng thẳng.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "das Auge",
    plural: "die Augen",
    phonetic: "/ˈaʊgə/",
    vietnamese: "Mắt",
    exampleGerman: "Das Auge tut weh, weil ich es gestern verletzt habe.",
    exampleVietnamese: "Mắt thì đau, vì hôm qua tôi đã làm tổn thương nó.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Augenbraue",
    plural: "die Augenbrauen",
    phonetic: "/ˈaʊgənˌbraʊə/",
    vietnamese: "Lông mày",
    exampleGerman: "Die Augenbrauen müssen regelmäßig gezupft werden.",
    exampleVietnamese: "Lông mày cần được nhổ đều đặn.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Wimper",
    plural: "die Wimpern",
    phonetic: "/ˈvɪmpɐ/",
    vietnamese: "Lông mi",
    exampleGerman: "Die Wimpern sind lang, weil sie mit Mascara betont werden.",
    exampleVietnamese: "Lông mi dài, vì chúng được tô điểm với mascara.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Nase",
    plural: "die Nasen",
    phonetic: "/ˈnaːzə/",
    vietnamese: "Mũi",
    exampleGerman: "Die Nase ist rot, weil ich erkältet bin.",
    exampleVietnamese: "Mũi tôi đỏ, vì tôi bị cảm lạnh.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "das Ohr",
    plural: "die Ohren",
    phonetic: "/oːr/",
    vietnamese: "Tai",
    exampleGerman: "Das Ohr hört alles, aber es kann nicht immer verstehen.",
    exampleVietnamese: "Tai nghe tất cả, nhưng không phải lúc nào cũng hiểu.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "der Mund",
    plural: "die Münder",
    phonetic: "/mʊnt/",
    vietnamese: "Miệng",
    exampleGerman: "Der Mund ist trocken, weil ich lange nicht gesprochen habe.",
    exampleVietnamese: "Miệng tôi khô, vì tôi đã không nói chuyện lâu.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Lippe",
    plural: "die Lippen",
    phonetic: "/ˈlɪpə/",
    vietnamese: "Môi",
    exampleGerman: "Die Lippen sind rot, weil ich Lippenstift trage.",
    exampleVietnamese: "Môi tôi đỏ, vì tôi đang thoa son môi.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "der Zahn",
    plural: "die Zähne",
    phonetic: "/tsaːn/",
    vietnamese: "Răng",
    exampleGerman: "Die Zähne sind gesund, weil ich jeden Tag putze.",
    exampleVietnamese: "Răng tôi khỏe mạnh, vì tôi đánh răng mỗi ngày.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Zunge",
    plural: "die Zungen",
    phonetic: "/ˈtsʊŋə/",
    vietnamese: "Lưỡi",
    exampleGerman: "Die Zunge ist empfindlich, weil sie bei der Verdauung hilft.",
    exampleVietnamese: "Lưỡi rất nhạy cảm, vì nó giúp trong quá trình tiêu hóa.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "das Kinn",
    plural: "die Kinne",
    phonetic: "/kɪn/",
    vietnamese: "Cằm",
    exampleGerman: "Das Kinn ist markant, und man sieht es deutlich.",
    exampleVietnamese: "Cằm rất nổi bật, và bạn có thể thấy rõ.",
    type: "Nomen",
    level: "A1",
  },
  {
    german: "die Wange",
    plural: "die Wangen",
    phonetic: "/ˈvaŋə/",
    vietnamese: "Má",
    exampleGerman: "Die Wange war rot, weil sie den ganzen Tag in der Sonne war.",
    exampleVietnamese: "Má tôi đỏ, vì tôi đã ở ngoài nắng cả ngày.",
    type: "Nomen",
    level: "A1",
  },
];
