import { NewsArticle } from './types';

export const mockArticles: NewsArticle[] = [
  {
    id: '1',
    title: 'Deutschland führt neue Energiepolitik ein',
    url: '#',
    content: `Die deutsche Bundesregierung hat heute ein umfassendes Energiepaket vorgestellt, das den Weg für eine nachhaltigere Zukunft ebnen soll. Die neuen Maßnahmen zielen darauf ab, den Anteil erneuerbarer Energien bis 2030 auf 80% zu steigern.`,
    excerpt: 'Die Bundesregierung plant umfassende Reformen im Energiesektor. Neue Gesetze sollen den Übergang zu erneuerbaren Energien beschleunigen.',
    publishedAt: '2024-02-15T10:30:00Z',
    category: 'politik',
    featured: true,
    wordCount: 850,
    imageUrl: 'https://picsum.photos/800/400?random=1'
  },
  {
    id: '2',
    title: 'Künstliche Intelligenz revolutioniert deutsche Industrie',
    url: '#',
    content: `Die deutsche Industrie steht vor einem technologischen Wandel. Künstliche Intelligenz (KI) hält Einzug in Fabriken und verändert fundamental die Art, wie produziert wird.`,
    excerpt: 'Neue KI-Technologien verändern die Produktionsprozesse in deutschen Unternehmen. Experten erwarten einen Produktivitätsschub von 30%.',
    publishedAt: '2024-02-14T14:15:00Z',
    category: 'technologie',
    featured: false,
    wordCount: 720,
    imageUrl: 'https://picsum.photos/800/400?random=2'
  },
  {
    id: '3',
    title: 'Neue Wohnungsbauinitiative für bezahlbaren Wohnraum',
    url: '#',
    content: `Deutschland startet eine der größten Wohnungsbauinitiativen der vergangenen Jahrzehnte. Das neue Programm soll den akuten Wohnungsmangel in Ballungsräumen bekämpfen.`,
    excerpt: 'Bundesregierung startet Programm für 400.000 neue Wohnungen. Fokus liegt auf nachhaltigen und bezahlbaren Lösungen.',
    publishedAt: '2024-02-13T09:45:00Z',
    category: 'gesellschaft',
    featured: false,
    wordCount: 680,
    imageUrl: 'https://picsum.photos/800/400?random=3'
  },
  {
    id: '4',
    title: 'Digitale Bildung: Schulen erhalten moderne Technologie',
    url: '#',
    content: `Deutschland investiert massiv in die digitale Ausstattung seiner Schulen. Ein neues Programm im Wert von 3 Milliarden Euro soll alle Bildungseinrichtungen mit moderner Technologie ausstatten.`,
    excerpt: 'Milliardenschweres Programm stattet deutsche Schulen mit neuester Technik aus. Tablets und interaktive Whiteboards für alle Klassenzimmer.',
    publishedAt: '2024-02-12T11:20:00Z',
    category: 'bildung',
    featured: true,
    wordCount: 920,
    imageUrl: 'https://picsum.photos/800/400?random=4'
  },
  {
    id: '5',
    title: 'Wirtschaftswachstum übertrifft Prognosen',
    url: '#',
    content: `Die deutsche Wirtschaft zeigt sich robuster als erwartet. Das Bruttoinlandsprodukt ist im vergangenen Quartal um 2,1% gewachsen und übertraf damit alle Expertenschätzungen.`,
    excerpt: 'Deutsche Wirtschaft wächst stärker als prognostiziert. Exportstärke und Binnenkonsum treiben das Wachstum an.',
    publishedAt: '2024-02-11T13:30:00Z',
    category: 'wirtschaft',
    featured: false,
    wordCount: 580,
    imageUrl: 'https://picsum.photos/800/400?random=5'
  },
  {
    id: '6',
    title: 'Tesla eröffnet neue Gigafactory in Berlin',
    url: '#',
    content: `Der Elektroautobauer Tesla hat heute offiziell seine neue Produktionsstätte in Berlin eröffnet. Die Fabrik soll zunächst 500.000 Fahrzeuge pro Jahr produzieren.`,
    excerpt: 'Tesla startet Produktion in Berlin-Brandenburg. Neue Arbeitsplätze und lokale Wertschöpfung im Fokus.',
    publishedAt: '2024-02-10T16:45:00Z',
    category: 'technologie',
    featured: false,
    wordCount: 450,
    imageUrl: 'https://picsum.photos/800/400?random=6'
  },
  {
    id: '7',
    title: 'Durchbruch in der Alzheimer-Forschung',
    url: '#',
    content: `Deutsche Wissenschaftler haben einen bedeutenden Fortschritt in der Alzheimer-Forschung erzielt. Ein neuer Therapieansatz könnte die Behandlung der Krankheit revolutionieren.`,
    excerpt: 'Forscher entwickeln neuen Ansatz zur Alzheimer-Behandlung. Klinische Studien zeigen vielversprechende Ergebnisse.',
    publishedAt: '2024-02-09T08:15:00Z',
    category: 'wissenschaft',
    featured: true,
    wordCount: 780,
    imageUrl: 'https://picsum.photos/800/400?random=7'
  },
  {
    id: '8',
    title: 'Neue Satelliten-Navigation für Europa',
    url: '#',
    content: `Europa stärkt seine Unabhängigkeit im Bereich der Satellitennavigation. Das Galileo-System wird mit zusätzlichen Satelliten erweitert.`,
    excerpt: 'Galileo-Programm wird ausgebaut. Europa wird unabhängiger von ausländischen Navigationssystemen.',
    publishedAt: '2024-02-08T12:00:00Z',
    category: 'technologie',
    featured: false,
    wordCount: 620,
    imageUrl: 'https://picsum.photos/800/400?random=8'
  },
  {
    id: '9',
    title: 'Deutschland qualifiziert sich für Fußball-WM',
    url: '#',
    content: `Die deutsche Fußballnationalmannschaft hat sich erfolgreich für die kommende Weltmeisterschaft qualifiziert. Nach einem spannenden Qualifikationsturnier steht das Team bereit.`,
    excerpt: 'DFB-Team löst WM-Ticket. Trainer und Spieler zeigen sich optimistisch für das Turnier.',
    publishedAt: '2024-02-07T20:30:00Z',
    category: 'sport',
    featured: false,
    wordCount: 520,
    imageUrl: 'https://picsum.photos/800/400?random=9'
  },
  {
    id: '10',
    title: 'Mietpreise in deutschen Städten stabilisieren sich',
    url: '#',
    content: `Nach Jahren kontinuierlicher Steigerungen zeigen die Mietpreise in deutschen Großstädten erste Anzeichen einer Stabilisierung.`,
    excerpt: 'Wohnungsmarkt entspannt sich leicht. Neue Bauvorhaben zeigen erste Wirkung auf die Preisgestaltung.',
    publishedAt: '2024-02-06T14:20:00Z',
    category: 'gesellschaft',
    featured: false,
    wordCount: 690,
    imageUrl: 'https://picsum.photos/800/400?random=10'
  },
  {
    id: '11',
    title: 'Lehrermangel: Neue Initiativen zeigen Wirkung',
    url: '#',
    content: `Deutschland kämpft erfolgreich gegen den Lehrermangel. Neue Ausbildungsprogramme und verbesserte Arbeitsbedingungen ziehen wieder mehr Menschen in den Beruf.`,
    excerpt: 'Bildungssektor erholt sich vom Lehrermangel. Innovative Programme locken Quereinsteiger an.',
    publishedAt: '2024-02-05T10:45:00Z',
    category: 'bildung',
    featured: false,
    wordCount: 580,
    imageUrl: 'https://picsum.photos/800/400?random=11'
  },
  {
    id: '12',
    title: 'Berlin bewirbt sich um Olympische Spiele 2036',
    url: '#',
    content: `Die deutsche Hauptstadt hat offiziell ihre Bewerbung für die Olympischen Sommerspiele 2036 eingereicht. Das Konzept setzt auf Nachhaltigkeit und Innovation.`,
    excerpt: 'Berlin will wieder Olympiastadt werden. Nachhaltiges Konzept im Mittelpunkt der Bewerbung.',
    publishedAt: '2024-02-04T15:30:00Z',
    category: 'sport',
    featured: true,
    wordCount: 710,
    imageUrl: 'https://picsum.photos/800/400?random=12'
  },
  {
    id: '13',
    title: 'Deutsche Musik erobert internationale Charts',
    url: '#',
    content: `Deutsche Künstler feiern internationale Erfolge. Mehrere Songs haben es in die Top 10 der globalen Streaming-Charts geschafft.`,
    excerpt: 'Deutscher Pop wird international erfolgreich. Streaming-Dienste verzeichnen steigende Zahlen.',
    publishedAt: '2024-02-03T18:15:00Z',
    category: 'kultur',
    featured: false,
    wordCount: 480,
    imageUrl: 'https://picsum.photos/800/400?random=13'
  },
  {
    id: '14',
    title: 'Quantencomputer: Deutschland investiert Milliarden',
    url: '#',
    content: `Deutschland startet eine der größten Investitionsoffensiven in der Quantentechnologie. Das neue Programm soll das Land an die Weltspitze bringen.`,
    excerpt: 'Milliardeninvestition in Quantentechnologie. Deutschland will führende Position in Zukunftstechnologie einnehmen.',
    publishedAt: '2024-02-02T11:00:00Z',
    category: 'wissenschaft',
    featured: false,
    wordCount: 850,
    imageUrl: 'https://picsum.photos/800/400?random=14'
  },
  {
    id: '15',
    title: 'Alpen: Neues Naturschutzprogramm gestartet',
    url: '#',
    content: `Ein ambitioniertes Naturschutzprogramm soll die einzigartige Alpenlandschaft für kommende Generationen bewahren. Internationale Zusammenarbeit im Fokus.`,
    excerpt: 'Grenzübergreifender Alpenschutz wird verstärkt. Neue Maßnahmen zum Erhalt der Biodiversität.',
    publishedAt: '2024-02-01T09:30:00Z',
    category: 'umwelt',
    featured: false,
    wordCount: 640,
    imageUrl: 'https://picsum.photos/800/400?random=15'
  }
];
