import { NewsArticle } from './types';

export const mockArticles: NewsArticle[] = [
  {
    id: '1',
    title: 'Deutschland führt neue Energiepolitik ein',
    url: '#',
    content: `Die deutsche Bundesregierung hat heute ein umfassendes Energiepaket vorgestellt, das den Weg für eine nachhaltigere Zukunft ebnen soll. Die neuen Maßnahmen zielen darauf ab, den Anteil erneuerbarer Energien bis 2030 auf 80% zu steigern.`,
    excerpt: 'Die Bundesregierung plant umfassende Reformen im Energiesektor. Neue Gesetze sollen den Übergang zu erneuerbaren Energien beschleunigen.',
    source: 'Anna Müller',
    publishedAt: '2024-02-15T10:30:00Z',
    category: 'politik',
    featured: true,
    wordCount: 850,
    imageUrl: 'https://via.placeholder.com/800x400/1e40af/ffffff?text=🏛️+Energiepolitik+Deutschland'
  },
  {
    id: '2',
    title: 'Künstliche Intelligenz revolutioniert deutsche Industrie',
    url: '#',
    content: `Die deutsche Industrie steht vor einem technologischen Wandel. Künstliche Intelligenz (KI) hält Einzug in Fabriken und verändert fundamental die Art, wie produziert wird.`,
    excerpt: 'Neue KI-Technologien verändern die Produktionsprozesse in deutschen Unternehmen. Experten erwarten einen Produktivitätsschub von 30%.',
    source: 'Dr. Michael Schmidt',
    publishedAt: '2024-02-14T14:15:00Z',
    category: 'technologie',
    featured: false,
    wordCount: 720,
    imageUrl: 'https://via.placeholder.com/800x400/059669/ffffff?text=🤖+KI+Industrie'
  },
  {
    id: '3',
    title: 'Neue Wohnungsbauinitiative für bezahlbaren Wohnraum',
    url: '#',
    content: `Deutschland startet eine der größten Wohnungsbauinitiativen der vergangenen Jahrzehnte. Das neue Programm soll den akuten Wohnungsmangel in Ballungsräumen bekämpfen.`,
    excerpt: 'Bundesregierung startet Programm für 400.000 neue Wohnungen. Fokus liegt auf nachhaltigen und bezahlbaren Lösungen.',
    source: 'Lisa Weber',
    publishedAt: '2024-02-13T09:45:00Z',
    category: 'gesellschaft',
    featured: false,
    wordCount: 680,
    imageUrl: 'https://via.placeholder.com/800x400/7c3aed/ffffff?text=🏠+Wohnungsbau'
  },
  {
    id: '4',
    title: 'Digitale Bildung: Schulen erhalten moderne Technologie',
    url: '#',
    content: `Deutschland investiert massiv in die digitale Ausstattung seiner Schulen. Ein neues Programm im Wert von 3 Milliarden Euro soll alle Bildungseinrichtungen mit moderner Technologie ausstatten.`,
    excerpt: 'Milliardenschweres Programm stattet deutsche Schulen mit neuester Technik aus. Tablets und interaktive Whiteboards für alle Klassenzimmer.',
    source: 'Prof. Dr. Elena Richter',
    publishedAt: '2024-02-12T11:20:00Z',
    category: 'bildung',
    featured: false,
    wordCount: 620,
    imageUrl: 'https://via.placeholder.com/800x400/dc2626/ffffff?text=💻+Digitale+Bildung'
  },
  {
    id: '5',
    title: 'Deutsche Wirtschaft wächst trotz globaler Herausforderungen',
    url: '#',
    content: `Die deutsche Wirtschaft zeigt sich robust gegenüber globalen Herausforderungen. Das Bruttoinlandsprodukt (BIP) wuchs im letzten Quartal um beeindruckende 2,1%.`,
    excerpt: 'BIP steigt um 2,1% im vergangenen Quartal. Exportstarke Branchen treiben das Wachstum an, trotz internationaler Unsicherheiten.',
    source: 'Dr. Marcus Fischer',
    publishedAt: '2024-02-11T16:00:00Z',
    category: 'wirtschaft',
    featured: false,
    wordCount: 580,
    imageUrl: 'https://via.placeholder.com/800x400/ea580c/ffffff?text=📈+Wirtschaftswachstum'
  },
  {
    id: '6',
    title: 'Tesla Gigafactory Berlin erreicht Rekordproduktion',
    url: '#',
    content: `Tesla hat in seiner Berliner Gigafactory einen neuen Produktionsrekord aufgestellt. Im Januar 2025 wurden erstmals mehr als 50.000 Model Y Fahrzeuge in einem Monat produziert.`,
    excerpt: 'Tesla Berlin erreicht 50.000 Fahrzeuge pro Monat und plant weitere Expansion. Neue Arbeitsplätze entstehen in Brandenburg.',
    source: 'Handelsblatt',
    publishedAt: '2024-02-10T08:15:00Z',
    category: 'wirtschaft',
    featured: false,
    wordCount: 520,
    imageUrl: 'https://via.placeholder.com/800x400/6b7280/ffffff?text=📰+Tesla+Berlin'
  },
  {
    id: '7',
    title: 'Alzheimer-Durchbruch: Deutsche Forscher entwickeln neue Therapie',
    url: '#',
    content: `Deutsche Wissenschaftler haben einen vielversprechenden Ansatz zur Behandlung von Alzheimer entwickelt. Die neue Immuntherapie könnte das Fortschreiten der Krankheit verlangsamen.`,
    excerpt: 'Wissenschaftler der Charité Berlin entwickeln neue Alzheimer-Behandlung mit vielversprechenden Ergebnissen.',
    source: 'Medical Tribune',
    publishedAt: '2024-02-09T14:00:00Z',
    category: 'wissenschaft',
    featured: false,
    wordCount: 480,
    imageUrl: 'https://via.placeholder.com/800x400/059669/ffffff?text=🧠+Alzheimer+Forschung'
  },
  {
    id: '8',
    title: 'Deutsches Satellitennavigationssystem geht online',
    url: '#',
    content: `Das europäische Galileo-System wird durch deutsche Technologie ergänzt. Neue Satelliten sorgen für zentimetergenaue Navigation in ganz Europa.`,
    excerpt: 'Deutsche Raumfahrttechnik revolutioniert Navigation - Galileo wird zentimetergenau.',
    source: 'DLR News',
    publishedAt: '2024-02-08T12:30:00Z',
    category: 'technologie',
    featured: false,
    wordCount: 420,
    imageUrl: 'https://via.placeholder.com/800x400/7c3aed/ffffff?text=🛰️+Satelliten+Navigation'
  },
  {
    id: '9',
    title: 'Fußball-WM 2026: Deutschland qualifiziert sich vorzeitig',
    url: '#',
    content: `Die deutsche Nationalmannschaft hat sich als erstes europäisches Team für die Fußball-WM 2026 qualifiziert. Der 3:0-Sieg gegen Italien sicherte den Gruppensieg.`,
    excerpt: 'DFB-Team löst erstes WM-Ticket für 2026 - Nagelsmann feiert Erfolg.',
    source: 'Kicker',
    publishedAt: '2024-02-07T20:45:00Z',
    category: 'sport',
    featured: false,
    wordCount: 380,
    imageUrl: 'https://via.placeholder.com/800x400/dc2626/ffffff?text=⚽+WM+Qualifikation'
  },
  {
    id: '10',
    title: 'Mietpreise in deutschen Städten erreichen Rekordhoch',
    url: '#',
    content: `Die Mietpreise in deutschen Großstädten sind erneut gestiegen. München führt mit durchschnittlich 18,50 Euro pro Quadratmeter, gefolgt von Frankfurt und Hamburg.`,
    excerpt: 'Wohnungsmarkt unter Druck - München mit 18,50 Euro/m² Spitzenreiter.',
    source: 'Immobilien Zeitung',
    publishedAt: '2024-02-06T16:20:00Z',
    category: 'gesellschaft',
    featured: false,
    wordCount: 340,
    imageUrl: 'https://via.placeholder.com/800x400/ea580c/ffffff?text=🏠+Mietpreise'
  },
  {
    id: '11',
    title: 'Lehrermangel: 40.000 Stellen unbesetzt',
    url: '#',
    content: `Deutschland kämpft mit akutem Lehrermangel. Besonders in MINT-Fächern und Grundschulen fehlen qualifizierte Lehrkräfte. Notmaßnahmen werden diskutiert.`,
    excerpt: 'Bildungskrise verschärft sich - 40.000 Lehrerstellen bundesweit vakant.',
    source: 'Bildungsportal',
    publishedAt: '2024-02-05T11:10:00Z',
    category: 'bildung',
    featured: false,
    wordCount: 320,
    imageUrl: 'https://via.placeholder.com/800x400/7c3aed/ffffff?text=👩‍🏫+Lehrermangel'
  },
  {
    id: '12',
    title: 'Berlin bewirbt sich um Olympische Spiele 2036',
    url: '#',
    content: `Berlin möchte Gastgeber der Olympischen Sommerspiele 2036 werden. Ein Konzept für nachhaltige Spiele soll überzeugen. Die Bewerbung steht unter dem Motto "Celebrating Humanity".`,
    excerpt: 'Berlin will Olympia 2036 ausrichten - Nachhaltiges Konzept im Fokus.',
    source: 'Tagesspiegel',
    publishedAt: '2024-02-04T09:30:00Z',
    category: 'sport',
    featured: false,
    wordCount: 360,
    imageUrl: 'https://via.placeholder.com/800x400/059669/ffffff?text=🏅+Olympia+Berlin'
  },
  {
    id: '13',
    title: 'Deutsche Musik erobert internationale Charts',
    url: '#',
    content: `Deutsche Künstler feiern weltweite Erfolge. Rammstein, AnnenMayKantereit und Apache 207 stehen in über 30 Ländern in den Top-Charts. Streaming-Zahlen explodieren.`,
    excerpt: 'German Music goes global - Deutsche Künstler erobern Weltcharts.',
    source: 'Musikexpress',
    publishedAt: '2024-02-03T15:45:00Z',
    category: 'kultur',
    featured: false,
    wordCount: 300,
    imageUrl: 'https://via.placeholder.com/800x400/6b7280/ffffff?text=🎵+Deutsche+Musik'
  },
  {
    id: '14',
    title: 'Quantencomputer "Made in Germany" startet Testbetrieb',
    url: '#',
    content: `Der erste deutsche Quantencomputer nimmt den Betrieb auf. Das System von IBM und Fraunhofer soll deutsche Forschung und Industrie revolutionieren.`,
    excerpt: 'Quantentechnologie in Deutschland - Erster Quantencomputer geht online.',
    source: 'Fraunhofer News',
    publishedAt: '2024-02-02T13:15:00Z',
    category: 'technologie',
    featured: false,
    wordCount: 280,
    imageUrl: 'https://via.placeholder.com/800x400/1e40af/ffffff?text=⚛️+Quantencomputer'
  },
  {
    id: '15',
    title: 'Biodiversität: Neues Schutzgebiet in den Alpen eingerichtet',
    url: '#',
    content: `Ein neues Naturschutzgebiet in den bayerischen Alpen soll bedrohte Arten schützen. Das 15.000 Hektar große Areal wird zum Refugium für Steinadler und Alpenmurmeltiere.`,
    excerpt: 'Naturschutz in Bayern - 15.000 Hektar neues Schutzgebiet in den Alpen.',
    source: 'Naturschutz Heute',
    publishedAt: '2024-02-01T10:00:00Z',
    category: 'umwelt',
    featured: false,
    wordCount: 260,
    imageUrl: 'https://via.placeholder.com/800x400/059669/ffffff?text=🏔️+Alpen+Naturschutz'
  }
];
